// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dex.proto

package com.tangem.blockchain.blockchains.binance.proto;

public interface SendOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transaction.Send)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .transaction.Send.Input inputs = 1;</code>
   */
  java.util.List<Send.Input>
      getInputsList();
  /**
   * <code>repeated .transaction.Send.Input inputs = 1;</code>
   */
  Send.Input getInputs(int index);
  /**
   * <code>repeated .transaction.Send.Input inputs = 1;</code>
   */
  int getInputsCount();
  /**
   * <code>repeated .transaction.Send.Input inputs = 1;</code>
   */
  java.util.List<? extends Send.InputOrBuilder>
      getInputsOrBuilderList();
  /**
   * <code>repeated .transaction.Send.Input inputs = 1;</code>
   */
  Send.InputOrBuilder getInputsOrBuilder(int index);

  /**
   * <code>repeated .transaction.Send.Output outputs = 2;</code>
   */
  java.util.List<Send.Output>
      getOutputsList();
  /**
   * <code>repeated .transaction.Send.Output outputs = 2;</code>
   */
  Send.Output getOutputs(int index);
  /**
   * <code>repeated .transaction.Send.Output outputs = 2;</code>
   */
  int getOutputsCount();
  /**
   * <code>repeated .transaction.Send.Output outputs = 2;</code>
   */
  java.util.List<? extends Send.OutputOrBuilder>
      getOutputsOrBuilderList();
  /**
   * <code>repeated .transaction.Send.Output outputs = 2;</code>
   */
  Send.OutputOrBuilder getOutputsOrBuilder(int index);
}
