name: Tests

on:
  pull_request:
    branches: 
    - 'release/**'
    - 'develop'
    - 'release-app_**'
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DVELOPMENT_ANDROID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Configure local.properties file
      run: echo sdk.dir = $ANDROID_HOME > local.properties
    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
    - name: Check codestyle
      run: |
        ./gradlew clean detekt
    - name: Build tests
      run: |
        ./gradlew assembleAndroidTest
    - name: Run unit tests
      run: ./gradlew test
      #    - name: Run Android tests
      #      uses: reactivecircus/android-emulator-runner@v2
      #      with:
      #        api-level: 30
      #        target: google_apis
      #        arch: x86
      #        script: ./gradlew connectedAndroidTest
    - name: Build notification
      if: failure()
      uses: adamkdean/simple-slack-notify@master
      with:
        channel: '#development-android'
        text: 'Neutral build #${{ github.run_number }} failed'
        color: 'danger'
        fields: |
          [{ "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]
